import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Noemi Platform Cap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Noemi Platform Cap</title>
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
